### ISSUE TITLE
Typing SQL quickly in SQL Editor allows an invalid table definition

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/dbsp#271] opened 2023-06-23 01:46 UTC
1. Navigate to SQL Editor.
2. Type in SQL as `create table foobar (mycol int)`
3. Without waiting for it to finish compiling change it to `create table foobar (mycol int, mycol varchar(32))` and complete the edits before (2) compilation completes
4. Editor will accept the invalid DDL definition

**Comment by lalithsuresh** [comment] 2023-06-23 17:59
Typing too fast also overwrites recent changes. It seems to overwrite the recent change up to the last point that was sent for compilation.

**Comment by gz** [comment] 2023-06-23 18:30
Yep I noticed this in the past as well. I think there is some race with fetching server state and getting client-input. Will have a look...

**Comment by mihaibudiu** [comment] 2023-06-23 18:31
Maybe "compile" should be a button, which freezes the UI.

**Comment by lalithsuresh** [comment] 2023-06-23 18:34
The compiler runs without the user prompt regularly. Which means if we freeze the UI, the user will be interrupted in the middle of typing.

Maybe the server state should not be updating the SQL editor while it's open.

**Comment by mihaibudiu** [comment] 2023-06-23 18:35
That's what I am proposing to change. The compiler should run only when the user clicks "Compile".
Then the user either has to press "cancel" or the code window is read-only until compilation is finished.

**Comment by gz** [comment] 2023-06-23 18:58
I'd argue it's less user-friendly to have to click a button (aka move hand to mouse), then move back to be able to type again.

Why is the current behavior bad (have things checked automatically whenever the user stops typing for a few seconds)? IMO you'll notice problems sooner. That's also what people from IDEs are used to (e.g., have type-check issues appear as they're typing)?

**Comment by mihaibudiu** [comment] 2023-06-23 19:00
The issue is that it doesn't work, that's what we are discussing here.
Even in the IDE I have to press "build" to build everything.

**Comment by gz** [comment] 2023-06-23 19:05
Yes but it doesn't work because there is a race (that's fixable without changing behavior). You're proposing to change the way it works (which is different from fixing the bug). 

In vscode you don't have to press build for example it gets rebuilt automatically as you type that's what I tried to mimick.

**Comment by gz** [comment] 2023-08-10 02:04
I hope this is fixed now I tried to reproduce for 5min but couldn't..

**Closed by gz** 2023-08-10 02:04 UTC
Labels: bug, Web Console
