### ISSUE TITLE
Add support for weights and upserts in input connectors

### ISSUE THREAD

**Issue by blp** [feldera/dbsp#347] opened 2023-07-12 18:46 UTC
It appears to me that existing input connectors produce records with a fixed weight of 1. This is fine for some input streams. For other kinds of input streams, it would be useful to support other semantics. The main ones that come to mind now:
* Allow a column to specify the record weight directly, to allow both insertions and retractions.
* With a set of columns designated as a key, implement "upsert" semantics.

**Comment by gz** [comment] 2023-07-14 21:15
This has the WEB UI label but it seems the issue is more about backend/API support. Ok to remove the label? And maybe once we solved this in the backend/dbsp we can come up with an issue for how to use this in the UI?

**Comment by blp** [comment] 2023-07-14 21:17
> Ok to remove the label?

Sure. I knew it wasn't exactly the correct label but I didn't know what was better.

**Comment by ryzhyk** [comment] 2023-08-09 19:39
This was partially implemented in recent JSON-related PRs. I will close this one and document missing bits (upsert support, support for deleting records from the UI) as new issues.

**Closed by ryzhyk** 2023-08-09 19:39 UTC
Labels: enhancement, API
