### ISSUE TITLE
Add a /dev/null output connector

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/dbsp#287] opened 2023-06-26 18:15 UTC
It'll be nice to add a /dev/null destination for any view to able to introspect the data in the UI.

**Comment by ryzhyk** [comment] 2023-06-26 18:38
This shouldn't be needed.  The UI should be able to introspect any view or table, whether it has connectors or not. Not sure why it doesn't today.

@gz

**Comment by mohsinbeg** [comment] 2023-06-26 19:15
Introspecting tables throws exception in docker and UI shows a spinner that never completes.

**Comment by ryzhyk** [comment] 2023-06-26 19:46
Yes, this feature hasn't been implemented yet (see #101)

**Comment by gz** [comment] 2023-08-22 17:23
closing as duplicate of #101

**Closed by gz** 2023-08-22 17:23 UTC
Labels: enhancement, Web Console
