### ISSUE TITLE
[JIT] double aggregate produces wrong result

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/dbsp#189] opened 2023-05-31 20:59 UTC
I stared at the produced code but couldn't figure out whether it's wrong. 
It's possible that the problem is on my side, but I don't have a good way to debug it - except simulating the execution on paper.
Is there a debug facility to trace the execution of the JIT code?
The query is `SELECT 20 / SUM(1), 20 / SUM(2) FROM T GROUP BY COL1`
Interestingly, if I run each of the aggregates separately I get the correct results.
Here is the diff in results:

```
R: RowLiteral { rows: [Nullable(Some(I32(10))), Nullable(Some(I32(5)))] }x1
L: RowLiteral { rows: [Nullable(Some(I32(10))), Nullable(Some(I32(10)))] }x1
```

The value for the second component is wrong (10 instead of 5), as if the division by 2 didn't happen.

```
#[test]
pub fn test0() {
    /* 
    7131 Source()
    7133 Map(7131)
        (t 1 input:[I32, F64, Bool, String, ?I32, ?F64], $retval_1 2 output:[I32, I32, I32])
        block 1()
            # t.0
            3 Load 1[0]
            # into Tuple3::new(t.0, 1i32, 2i32).0
            4 Store 2[0]=3
            5 Constant 1i32
            # into Tuple3::new(t.0, 1i32, 2i32).1
            6 Store 2[1]=5
            7 Constant 2i32
            # into Tuple3::new(t.0, 1i32, 2i32).2
            8 Store 2[2]=7
            return #
    7136 IndexWith(7133)
        (t 1 input:[I32, I32, I32], $retval_1 2 output:[I32], $retval_2 3 output:[I32, I32, I32])
        block 1()
            # t.0
            4 Load 1[0]
            # into Tuple1::new(t.0).0
            5 Store 2[0]=4
            # t.0
            6 Load 1[0]
            # into Tuple3::new(t.0, t.1, t.2).0
            7 Store 3[0]=6
            # t.1
            8 Load 1[1]
            # into Tuple3::new(t.0, t.1, t.2).1
            9 Store 3[1]=8
            # t.2
            10 Load 1[2]
            # into Tuple3::new(t.0, t.1, t.2).2
            11 Store 3[2]=10
            return #
    7147 Fold(7136)
        init
            [None::<i32>, None::<i32>]
        step
            (a 1 inout:[?I32, ?I32], v 2 input:[I32, I32, I32], w 3 input:[I32])
            block 1()
                # w.0
                4 Load 3[0]
                jump 2()
            block 2()
                # a.0
                5 Load 1[0]
                6 IsNull 1[0]
                # v.1
                7 Load 2[1]
                # v.1.mul_by_ref(&w)
                8 7 Mul 4
                if 6 then 3() else 4()
            block 3()
                9 Constant false
                jump 5(8, 9)
            block 4()
                # agg_plus_N_(a.0, v.1.mul_by_ref(&w))
                10 5 Add 8
                11 Constant false
                jump 5(10, 11)
            block 5(12, 13)
                jump 6()
            block 6()
                jump 7()
            block 7()
                # a.1
                14 Load 1[1]
                15 IsNull 1[1]
                # v.2
                16 Load 2[2]
                # v.2.mul_by_ref(&w)
                17 16 Mul 4
                if 15 then 8() else 9()
            block 8()
                18 Constant false
                jump 10(17, 18)
            block 9()
                # agg_plus_N_(a.1, v.2.mul_by_ref(&w))
                19 14 Add 17
                20 Constant false
                jump 10(19, 20)
            block 10(21, 22)
                jump 11()
            block 11()
                # into Tuple2::new(tmp0, tmp1).0
                23 Store 1[0]=12
                24 SetNull 1[0]=13
                # into Tuple2::new(tmp0, tmp1).1
                25 Store 1[1]=21
                26 SetNull 1[1]=22
                return #
        finish
            (p_0 1 input:[?I32], p_1 2 input:[?I32], $retval_2 3 output:[?I32, ?I32])
            block 1()
                # p_0.0
                4 Load 1[0]
                5 IsNull 1[0]
                # p_1.0
                6 Load 2[0]
                7 IsNull 2[0]
                # into Tuple2::new(tmp0, tmp1).0
                8 Store 3[0]=4
                9 SetNull 3[0]=5
                # into Tuple2::new(tmp0, tmp1).1
                10 Store 3[1]=6
                11 SetNull 3[1]=7
                return #
    7149 Map(7147)
        (p_2 1 input:[I32], p_3 2 input:[?I32, ?I32], $retval_2 3 output:[I32, I32, I32])
        block 1()
            # p_2.0
            4 Load 1[0]
            # into Tuple3::new(p_2.0, cast_to_i32_i32N(p_3.0), cast_to_i32_i32N(p_3.1)).0
            5 Store 3[0]=4
            # p_3.0
            6 Load 2[0]
            7 IsNull 2[0]
            # into Tuple3::new(p_2.0, cast_to_i32_i32N(p_3.0), cast_to_i32_i32N(p_3.1)).1
            8 Store 3[1]=6
            # p_3.1
            9 Load 2[1]
            10 IsNull 2[1]
            # into Tuple3::new(p_2.0, cast_to_i32_i32N(p_3.0), cast_to_i32_i32N(p_3.1)).2
            11 Store 3[2]=9
            return #
    7154 Map(7149)
        (t 1 input:[I32, I32, I32], $retval_1 2 output:[?I32, ?I32])
        block 1()
            3 Constant 20i32
            # t.1
            4 Load 1[1]
            5 Constant 0i32
            6 5 Eq 4
            if 6 then 2() else 3()
        block 2()
            7 Constant true
            jump 4(7, 5)
        block 3()
            8 Constant false
            # div_i32_i32(20i32, t.1)
            9 3 Div 4
            jump 4(8, 9)
        block 4(10, 11)
            # into Tuple2::new(div_i32_i32(20i32, t.1), div_i32_i32(20i32, t.2)).0
            12 Store 2[0]=11
            13 SetNull 2[0]=10
            14 Constant 20i32
            # t.2
            15 Load 1[2]
            16 Constant 0i32
            17 16 Eq 15
            if 17 then 5() else 6()
        block 5()
            18 Constant true
            jump 7(18, 16)
        block 6()
            19 Constant false
            # div_i32_i32(20i32, t.2)
            20 14 Div 15
            jump 7(19, 20)
        block 7(21, 22)
            # into Tuple2::new(div_i32_i32(20i32, t.1), div_i32_i32(20i32, t.2)).1
            23 Store 2[1]=22
            24 SetNull 2[1]=21
            return #
    7157 Sink(7154)
     */
    const CIRCUIT: &str = r#"{
      "nodes" : {
        "7131" : {
          "Source" : {
            "layout" : 1,
            "table" : "T"
          }
        },
        "7133" : {
          "Map" : {
            "input" : 7131,
            "map_fn" : {
              "args" : [ {
                "id" : 1,
                "layout" : 1,
                "flags" : "input"
              }, {
                "id" : 2,
                "layout" : 2,
                "flags" : "output"
              } ],
              "ret" : "Unit",
              "entry_block" : 1,
              "blocks" : {
                "1" : {
                  "id" : 1,
                  "body" : [ [ 3, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 1,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ], [ 4, {
                    "Store" : {
                      "target" : 2,
                      "target_layout" : 2,
                      "column" : 0,
                      "value" : {
                        "Expr" : 3
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 5, {
                    "Constant" : {
                      "I32" : 1
                    }
                  } ], [ 6, {
                    "Store" : {
                      "target" : 2,
                      "target_layout" : 2,
                      "column" : 1,
                      "value" : {
                        "Expr" : 5
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 7, {
                    "Constant" : {
                      "I32" : 2
                    }
                  } ], [ 8, {
                    "Store" : {
                      "target" : 2,
                      "target_layout" : 2,
                      "column" : 2,
                      "value" : {
                        "Expr" : 7
                      },
                      "value_type" : "I32"
                    }
                  } ] ],
                  "terminator" : {
                    "Return" : {
                      "value" : {
                        "Imm" : "Unit"
                      }
                    }
                  },
                  "params" : [ ]
                }
              }
            },
            "input_layout" : {
              "Set" : 1
            },
            "output_layout" : {
              "Set" : 2
            }
          }
        },
        "7136" : {
          "IndexWith" : {
            "input" : 7133,
            "index_fn" : {
              "args" : [ {
                "id" : 1,
                "layout" : 2,
                "flags" : "input"
              }, {
                "id" : 2,
                "layout" : 3,
                "flags" : "output"
              }, {
                "id" : 3,
                "layout" : 2,
                "flags" : "output"
              } ],
              "ret" : "Unit",
              "entry_block" : 1,
              "blocks" : {
                "1" : {
                  "id" : 1,
                  "body" : [ [ 4, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 2,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ], [ 5, {
                    "Store" : {
                      "target" : 2,
                      "target_layout" : 3,
                      "column" : 0,
                      "value" : {
                        "Expr" : 4
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 6, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 2,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ], [ 7, {
                    "Store" : {
                      "target" : 3,
                      "target_layout" : 2,
                      "column" : 0,
                      "value" : {
                        "Expr" : 6
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 8, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 2,
                      "column" : 1,
                      "column_type" : "I32"
                    }
                  } ], [ 9, {
                    "Store" : {
                      "target" : 3,
                      "target_layout" : 2,
                      "column" : 1,
                      "value" : {
                        "Expr" : 8
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 10, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 2,
                      "column" : 2,
                      "column_type" : "I32"
                    }
                  } ], [ 11, {
                    "Store" : {
                      "target" : 3,
                      "target_layout" : 2,
                      "column" : 2,
                      "value" : {
                        "Expr" : 10
                      },
                      "value_type" : "I32"
                    }
                  } ] ],
                  "terminator" : {
                    "Return" : {
                      "value" : {
                        "Imm" : "Unit"
                      }
                    }
                  },
                  "params" : [ ]
                }
              }
            },
            "key_layout" : 4,
            "value_layout" : 2
          }
        },
        "7147" : {
          "Fold" : {
            "input" : 7136,
            "acc_layout" : 5,
            "step_layout" : 2,
            "output_layout" : 5,
            "finish_fn" : {
              "args" : [ {
                "id" : 1,
                "layout" : 6,
                "flags" : "input"
              }, {
                "id" : 2,
                "layout" : 6,
                "flags" : "input"
              }, {
                "id" : 3,
                "layout" : 5,
                "flags" : "output"
              } ],
              "ret" : "Unit",
              "entry_block" : 1,
              "blocks" : {
                "1" : {
                  "id" : 1,
                  "body" : [ [ 4, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 6,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ], [ 5, {
                    "IsNull" : {
                      "target" : 1,
                      "target_layout" : 6,
                      "column" : 0
                    }
                  } ], [ 6, {
                    "Load" : {
                      "source" : 2,
                      "source_layout" : 6,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ], [ 7, {
                    "IsNull" : {
                      "target" : 2,
                      "target_layout" : 6,
                      "column" : 0
                    }
                  } ], [ 8, {
                    "Store" : {
                      "target" : 3,
                      "target_layout" : 5,
                      "column" : 0,
                      "value" : {
                        "Expr" : 4
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 9, {
                    "SetNull" : {
                      "target" : 3,
                      "target_layout" : 5,
                      "column" : 0,
                      "is_null" : {
                        "Expr" : 5
                      }
                    }
                  } ], [ 10, {
                    "Store" : {
                      "target" : 3,
                      "target_layout" : 5,
                      "column" : 1,
                      "value" : {
                        "Expr" : 6
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 11, {
                    "SetNull" : {
                      "target" : 3,
                      "target_layout" : 5,
                      "column" : 1,
                      "is_null" : {
                        "Expr" : 7
                      }
                    }
                  } ] ],
                  "terminator" : {
                    "Return" : {
                      "value" : {
                        "Imm" : "Unit"
                      }
                    }
                  },
                  "params" : [ ]
                }
              }
            },
            "step_fn" : {
              "args" : [ {
                "id" : 1,
                "layout" : 5,
                "flags" : "inout"
              }, {
                "id" : 2,
                "layout" : 2,
                "flags" : "input"
              }, {
                "id" : 3,
                "layout" : 3,
                "flags" : "input"
              } ],
              "ret" : "Unit",
              "entry_block" : 1,
              "blocks" : {
                "1" : {
                  "id" : 1,
                  "body" : [ [ 4, {
                    "Load" : {
                      "source" : 3,
                      "source_layout" : 3,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 2,
                      "params" : [ ]
                    }
                  },
                  "params" : [ ]
                },
                "2" : {
                  "id" : 2,
                  "body" : [ [ 5, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 5,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ], [ 6, {
                    "IsNull" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 0
                    }
                  } ], [ 7, {
                    "Load" : {
                      "source" : 2,
                      "source_layout" : 2,
                      "column" : 1,
                      "column_type" : "I32"
                    }
                  } ], [ 8, {
                    "BinOp" : {
                      "lhs" : 7,
                      "rhs" : 4,
                      "kind" : "Mul",
                      "operand_ty" : "I32"
                    }
                  } ] ],
                  "terminator" : {
                    "Branch" : {
                      "cond" : {
                        "Expr" : 6
                      },
                      "true_params" : [ ],
                      "false_params" : [ ],
                      "falsy" : 4,
                      "truthy" : 3
                    }
                  },
                  "params" : [ ]
                },
                "3" : {
                  "id" : 3,
                  "body" : [ [ 9, {
                    "Constant" : {
                      "Bool" : false
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 5,
                      "params" : [ 8, 9 ]
                    }
                  },
                  "params" : [ ]
                },
                "4" : {
                  "id" : 4,
                  "body" : [ [ 10, {
                    "BinOp" : {
                      "lhs" : 5,
                      "rhs" : 8,
                      "kind" : "Add",
                      "operand_ty" : "I32"
                    }
                  } ], [ 11, {
                    "Constant" : {
                      "Bool" : false
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 5,
                      "params" : [ 10, 11 ]
                    }
                  },
                  "params" : [ ]
                },
                "5" : {
                  "id" : 5,
                  "body" : [ ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 6,
                      "params" : [ ]
                    }
                  },
                  "params" : [ [ 12, {
                    "Column" : "I32"
                  } ], [ 13, {
                    "Column" : "Bool"
                  } ] ]
                },
                "6" : {
                  "id" : 6,
                  "body" : [ ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 7,
                      "params" : [ ]
                    }
                  },
                  "params" : [ ]
                },
                "7" : {
                  "id" : 7,
                  "body" : [ [ 14, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 5,
                      "column" : 1,
                      "column_type" : "I32"
                    }
                  } ], [ 15, {
                    "IsNull" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 1
                    }
                  } ], [ 16, {
                    "Load" : {
                      "source" : 2,
                      "source_layout" : 2,
                      "column" : 2,
                      "column_type" : "I32"
                    }
                  } ], [ 17, {
                    "BinOp" : {
                      "lhs" : 16,
                      "rhs" : 4,
                      "kind" : "Mul",
                      "operand_ty" : "I32"
                    }
                  } ] ],
                  "terminator" : {
                    "Branch" : {
                      "cond" : {
                        "Expr" : 15
                      },
                      "true_params" : [ ],
                      "false_params" : [ ],
                      "falsy" : 9,
                      "truthy" : 8
                    }
                  },
                  "params" : [ ]
                },
                "8" : {
                  "id" : 8,
                  "body" : [ [ 18, {
                    "Constant" : {
                      "Bool" : false
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 10,
                      "params" : [ 17, 18 ]
                    }
                  },
                  "params" : [ ]
                },
                "9" : {
                  "id" : 9,
                  "body" : [ [ 19, {
                    "BinOp" : {
                      "lhs" : 14,
                      "rhs" : 17,
                      "kind" : "Add",
                      "operand_ty" : "I32"
                    }
                  } ], [ 20, {
                    "Constant" : {
                      "Bool" : false
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 10,
                      "params" : [ 19, 20 ]
                    }
                  },
                  "params" : [ ]
                },
                "10" : {
                  "id" : 10,
                  "body" : [ ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 11,
                      "params" : [ ]
                    }
                  },
                  "params" : [ [ 21, {
                    "Column" : "I32"
                  } ], [ 22, {
                    "Column" : "Bool"
                  } ] ]
                },
                "11" : {
                  "id" : 11,
                  "body" : [ [ 23, {
                    "Store" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 0,
                      "value" : {
                        "Expr" : 12
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 24, {
                    "SetNull" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 0,
                      "is_null" : {
                        "Expr" : 13
                      }
                    }
                  } ], [ 25, {
                    "Store" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 1,
                      "value" : {
                        "Expr" : 21
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 26, {
                    "SetNull" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 1,
                      "is_null" : {
                        "Expr" : 22
                      }
                    }
                  } ] ],
                  "terminator" : {
                    "Return" : {
                      "value" : {
                        "Imm" : "Unit"
                      }
                    }
                  },
                  "params" : [ ]
                }
              }
            },
            "init" : {
              "rows" : [ {
                "Nullable" : null
              }, {
                "Nullable" : null
              } ]
            }
          }
        },
        "7149" : {
          "Map" : {
            "input" : 7147,
            "map_fn" : {
              "args" : [ {
                "id" : 1,
                "layout" : 4,
                "flags" : "input"
              }, {
                "id" : 2,
                "layout" : 5,
                "flags" : "input"
              }, {
                "id" : 3,
                "layout" : 2,
                "flags" : "output"
              } ],
              "ret" : "Unit",
              "entry_block" : 1,
              "blocks" : {
                "1" : {
                  "id" : 1,
                  "body" : [ [ 4, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 4,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ], [ 5, {
                    "Store" : {
                      "target" : 3,
                      "target_layout" : 2,
                      "column" : 0,
                      "value" : {
                        "Expr" : 4
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 6, {
                    "Load" : {
                      "source" : 2,
                      "source_layout" : 5,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ], [ 7, {
                    "IsNull" : {
                      "target" : 2,
                      "target_layout" : 5,
                      "column" : 0
                    }
                  } ], [ 8, {
                    "Store" : {
                      "target" : 3,
                      "target_layout" : 2,
                      "column" : 1,
                      "value" : {
                        "Expr" : 6
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 9, {
                    "Load" : {
                      "source" : 2,
                      "source_layout" : 5,
                      "column" : 1,
                      "column_type" : "I32"
                    }
                  } ], [ 10, {
                    "IsNull" : {
                      "target" : 2,
                      "target_layout" : 5,
                      "column" : 1
                    }
                  } ], [ 11, {
                    "Store" : {
                      "target" : 3,
                      "target_layout" : 2,
                      "column" : 2,
                      "value" : {
                        "Expr" : 9
                      },
                      "value_type" : "I32"
                    }
                  } ] ],
                  "terminator" : {
                    "Return" : {
                      "value" : {
                        "Imm" : "Unit"
                      }
                    }
                  },
                  "params" : [ ]
                }
              }
            },
            "input_layout" : {
              "Map" : [ 4, 5 ]
            },
            "output_layout" : {
              "Set" : 2
            }
          }
        },
        "7154" : {
          "Map" : {
            "input" : 7149,
            "map_fn" : {
              "args" : [ {
                "id" : 1,
                "layout" : 2,
                "flags" : "input"
              }, {
                "id" : 2,
                "layout" : 5,
                "flags" : "output"
              } ],
              "ret" : "Unit",
              "entry_block" : 1,
              "blocks" : {
                "1" : {
                  "id" : 1,
                  "body" : [ [ 3, {
                    "Constant" : {
                      "I32" : 20
                    }
                  } ], [ 4, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 2,
                      "column" : 1,
                      "column_type" : "I32"
                    }
                  } ], [ 5, {
                    "Constant" : {
                      "I32" : 0
                    }
                  } ], [ 6, {
                    "BinOp" : {
                      "lhs" : 5,
                      "rhs" : 4,
                      "kind" : "Eq",
                      "operand_ty" : "I32"
                    }
                  } ] ],
                  "terminator" : {
                    "Branch" : {
                      "cond" : {
                        "Expr" : 6
                      },
                      "true_params" : [ ],
                      "false_params" : [ ],
                      "falsy" : 3,
                      "truthy" : 2
                    }
                  },
                  "params" : [ ]
                },
                "2" : {
                  "id" : 2,
                  "body" : [ [ 7, {
                    "Constant" : {
                      "Bool" : true
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 4,
                      "params" : [ 7, 5 ]
                    }
                  },
                  "params" : [ ]
                },
                "3" : {
                  "id" : 3,
                  "body" : [ [ 8, {
                    "Constant" : {
                      "Bool" : false
                    }
                  } ], [ 9, {
                    "BinOp" : {
                      "lhs" : 3,
                      "rhs" : 4,
                      "kind" : "Div",
                      "operand_ty" : "I32"
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 4,
                      "params" : [ 8, 9 ]
                    }
                  },
                  "params" : [ ]
                },
                "4" : {
                  "id" : 4,
                  "body" : [ [ 12, {
                    "Store" : {
                      "target" : 2,
                      "target_layout" : 5,
                      "column" : 0,
                      "value" : {
                        "Expr" : 11
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 13, {
                    "SetNull" : {
                      "target" : 2,
                      "target_layout" : 5,
                      "column" : 0,
                      "is_null" : {
                        "Expr" : 10
                      }
                    }
                  } ], [ 14, {
                    "Constant" : {
                      "I32" : 20
                    }
                  } ], [ 15, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 2,
                      "column" : 2,
                      "column_type" : "I32"
                    }
                  } ], [ 16, {
                    "Constant" : {
                      "I32" : 0
                    }
                  } ], [ 17, {
                    "BinOp" : {
                      "lhs" : 16,
                      "rhs" : 15,
                      "kind" : "Eq",
                      "operand_ty" : "I32"
                    }
                  } ] ],
                  "terminator" : {
                    "Branch" : {
                      "cond" : {
                        "Expr" : 17
                      },
                      "true_params" : [ ],
                      "false_params" : [ ],
                      "falsy" : 6,
                      "truthy" : 5
                    }
                  },
                  "params" : [ [ 10, {
                    "Column" : "Bool"
                  } ], [ 11, {
                    "Column" : "I32"
                  } ] ]
                },
                "5" : {
                  "id" : 5,
                  "body" : [ [ 18, {
                    "Constant" : {
                      "Bool" : true
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 7,
                      "params" : [ 18, 16 ]
                    }
                  },
                  "params" : [ ]
                },
                "6" : {
                  "id" : 6,
                  "body" : [ [ 19, {
                    "Constant" : {
                      "Bool" : false
                    }
                  } ], [ 20, {
                    "BinOp" : {
                      "lhs" : 14,
                      "rhs" : 15,
                      "kind" : "Div",
                      "operand_ty" : "I32"
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 7,
                      "params" : [ 19, 20 ]
                    }
                  },
                  "params" : [ ]
                },
                "7" : {
                  "id" : 7,
                  "body" : [ [ 23, {
                    "Store" : {
                      "target" : 2,
                      "target_layout" : 5,
                      "column" : 1,
                      "value" : {
                        "Expr" : 22
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 24, {
                    "SetNull" : {
                      "target" : 2,
                      "target_layout" : 5,
                      "column" : 1,
                      "is_null" : {
                        "Expr" : 21
                      }
                    }
                  } ] ],
                  "terminator" : {
                    "Return" : {
                      "value" : {
                        "Imm" : "Unit"
                      }
                    }
                  },
                  "params" : [ [ 21, {
                    "Column" : "Bool"
                  } ], [ 22, {
                    "Column" : "I32"
                  } ] ]
                }
              }
            },
            "input_layout" : {
              "Set" : 2
            },
            "output_layout" : {
              "Set" : 5
            }
          }
        },
        "7157" : {
          "Sink" : {
            "input" : 7154,
            "comment" : "CREATE VIEW V AS SELECT 20 / SUM(1), 20 / SUM(2) FROM T GROUP BY COL1",
            "input_layout" : {
              "Set" : 5
            }
          }
        }
      },
      "layouts" : {
        "5" : {
          "columns" : [ {
            "nullable" : true,
            "ty" : "I32"
          }, {
            "nullable" : true,
            "ty" : "I32"
          } ]
        },
        "1" : {
          "columns" : [ {
            "nullable" : false,
            "ty" : "I32"
          }, {
            "nullable" : false,
            "ty" : "F64"
          }, {
            "nullable" : false,
            "ty" : "Bool"
          }, {
            "nullable" : false,
            "ty" : "String"
          }, {
            "nullable" : true,
            "ty" : "I32"
          }, {
            "nullable" : true,
            "ty" : "F64"
          } ]
        },
        "2" : {
          "columns" : [ {
            "nullable" : false,
            "ty" : "I32"
          }, {
            "nullable" : false,
            "ty" : "I32"
          }, {
            "nullable" : false,
            "ty" : "I32"
          } ]
        },
        "3" : {
          "columns" : [ {
            "nullable" : false,
            "ty" : "I32"
          } ]
        },
        "4" : {
          "columns" : [ {
            "nullable" : false,
            "ty" : "I32"
          } ]
        },
        "6" : {
          "columns" : [ {
            "nullable" : true,
            "ty" : "I32"
          } ]
        }
      }
    }"#;
    let graph = serde_json::from_str::<SqlGraph>(CIRCUIT).unwrap().rematerialize();
    let graph_nodes = graph.nodes();
    let mut demands = Demands::new();
    let T_id = NodeId::new(7131u32);
    let T_layout = (graph_nodes[&T_id]).clone().unwrap_source().layout();
    let mut circuit = DbspCircuit::new(graph, true, 1usize, CodegenConfig::debug(), demands);
    circuit.append_input(T_id, &Set(vec!(
        (RowLiteral::new(vec!(
            NonNull(Constant::I32(10i32)), NonNull(Constant::F64(12.0)), NonNull(Constant::Bool(true)), NonNull(Constant::String(String::from("Hi"))), NullableConstant::null(), NullableConstant::null(), )), 1i32, ), (RowLiteral::new(vec!(
            NonNull(Constant::I32(10i32)), NonNull(Constant::F64(1.0)), NonNull(Constant::Bool(false)), NonNull(Constant::String(String::from("Hi"))), Nullable(Some(Constant::I32(1i32))), Nullable(Some(Constant::F64(0.0))), )), 1i32, ), )));
    circuit.step().unwrap();
    let V = circuit.consolidate_output(NodeId::new(7157u32));
    assert!(must_equal_sc(&V, &Set(vec!(
        (RowLiteral::new(vec!(
            Nullable(Some(Constant::I32(10i32))), Nullable(Some(Constant::I32(5i32))), )), 1i32, ), ))));
    circuit.kill().unwrap();
}
```

**Comment by Kixiron** [comment] 2023-06-03 17:38
Ah, the issue is that `finish_fn` has three parameters when it should have two

**Comment by mihaibudiu** [comment] 2023-06-05 17:25
Indeed. However, an error message saying that would be great.
In general I think we cannot trust that the JSON comes from our compiler, so we'll have to validate it.

**Comment by ryzhyk** [comment] 2023-07-03 20:12
@mihaibudiu , ok to close this?

**Comment by mihaibudiu** [comment] 2023-07-03 20:57
As I said in a comment above, in general panics are probably not ideal for handling malformed code.
We can close it if this particular malformed code will cause an error report instead of a crash.

**Closed** 2023-07-05 14:04 UTC
Labels: bug, JIT
